### ISSUE TITLE
Add Vedo sensors

### ISSUE THREAD

**Issue by Vincenzopica** [gicamm/homeassistant-comelit#42] opened 2023-04-09 06:08 UTC
Hello, can you see the status of the alarm zones?

**Comment by gicamm** [comment] 2023-04-11 07:31
Hi Vincenzo,
the integration already supports zones.
The alarm_control_panel entity allows arming/disarming it.

**Comment by Vincenzopica** [comment] 2023-04-11 08:44
turn on turn off it does, what I would like to see is the status of the zones, for example, kitchen window open or closed etc etc

**Comment by gicamm** [comment] 2023-04-11 15:21
It will come later. There were issues with that, so I disabled this feature.

**Comment by Vincenzopica** [comment] 2023-04-11 16:27
thank you very much

**Comment by MarksLiveMusic** [comment] 2023-04-14 16:02
Hi and thank you for the integration! It will be incredible to expose Vedo sensors, so we can use motion sensors for lights and other scenarios! I can confirm now that integration works as expected with zones too. I will wait and thank you again.

**Comment by maurilloh** [comment] 2023-06-07 10:19
Hi Gicamm,

Any news about?

> e status of the zones

**Comment by gicamm** [comment] 2023-06-07 12:44
Hi, I hope to expose vedo binary sensors asap. However, the main issue will be testing the feature. Before releasing the part, it would be helpful if you could try it with me.

**Comment by Vincenzopica** [comment] 2023-06-07 12:47
> Salve, spero di esporre al più presto i sensori binari vedo. Tuttavia, il problema principale sarà testare la funzionalità. Prima di rilasciare la parte, sarebbe utile se potessi provarla con me.

Hi, I'd be happy to be a tester

**Comment by Vincenzopica** [comment] 2023-06-07 12:49
> Hi, I hope to expose vedo binary sensors asap. However, the main issue will be testing the feature. Before releasing the part, it would be helpful if you could try it with me.

Hi, I'd be happy to be a tester

**Comment by maurilloh** [comment] 2023-06-07 12:51
> > Hi, I hope to expose vedo binary sensors asap. However, the main issue will be testing the feature. Before releasing the part, it would be helpful if you could try it with me.
> 
> Hi, I'd be happy to be a tester

me too

**Comment by maurilloh** [comment] 2023-06-08 08:55
> I completed the changes. The integration is [here](https://github.com/gicamm/homeassistant-comelit/archive/refs/heads/42-add-vedo-sensors.zip)
> 
> The configuration should be something like below.
> 
> ```
> vedo:
>   host: X.X.X.X
>   port: 80
>   password: xxxxxx
>   scan_interval: 30
>   binary_sensors: enable
> ```
> 
> You need to enable binary sensors (binary_sensors: enable) You can reduce the scan_interval to get new data more frequently. 30 is too much for motion sensors.
> 
> You'll see new entities binary_sensor.comelit_vedo_xxx

Hi Gicamm

I have replace the integration with the new ones and add the binary_sensors line but nothing appear

**Comment by Vincenzopica** [comment] 2023-06-08 17:11
> Ho completato le modifiche. L'integrazione è [qui](https://github.com/gicamm/homeassistant-comelit/archive/refs/heads/42-add-vedo-sensors.zip)
> 
> La configurazione dovrebbe essere simile alla seguente.
> 
> ```
> vedo:
>   host: X.X.X.X
>   port: 80
>   password: xxxxxx
>   scan_interval: 30
>   binary_sensors: enable
> ```
> 
> È necessario abilitare i sensori binari (binary_sensors: enable) È possibile ridurre scan_interval per ottenere nuovi dati più frequentemente. 30 è troppo per i sensori di movimento.
> 
> Vedrai nuove entità binary_sensor.comelit_vedo_xxx

How do I install the new integration?

**Comment by gicamm** [comment] 2023-06-08 18:06
You need to put the 'comelit' under the custom_components/ folder. Then you need to update the configuration.yml file.

> > Ho completato le modifiche. L'integrazione è [qui](https://github.com/gicamm/homeassistant-comelit/archive/refs/heads/42-add-vedo-sensors.zip)
> > La configurazione dovrebbe essere simile alla seguente.
> > ```
> > vedo:
> >   host: X.X.X.X
> >   port: 80
> >   password: xxxxxx
> >   scan_interval: 30
> >   binary_sensors: enable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > È necessario abilitare i sensori binari (binary_sensors: enable) È possibile ridurre scan_interval per ottenere nuovi dati più frequentemente. 30 è troppo per i sensori di movimento.
> > Vedrai nuove entità binary_sensor.comelit_vedo_xxx
> 
> How do I install the new integration?

You need to put the 'comelit' under the custom_components/ folder. Then you need to update the configuration.yml file.

**Comment by maurilloh** [comment] 2023-06-08 18:45
> You need to put the 'comelit' under the custom_components/ folder. Then you need to update the configuration.yml file.
> 
> > > Ho completato le modifiche. L'integrazione è [qui](https://github.com/gicamm/homeassistant-comelit/archive/refs/heads/42-add-vedo-sensors.zip)
> > > La configurazione dovrebbe essere simile alla seguente.
> > > ```
> > > vedo:
> > >   host: X.X.X.X
> > >   port: 80
> > >   password: xxxxxx
> > >   scan_interval: 30
> > >   binary_sensors: enable
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > È necessario abilitare i sensori binari (binary_sensors: enable) È possibile ridurre scan_interval per ottenere nuovi dati più frequentemente. 30 è troppo per i sensori di movimento.
> > > Vedrai nuove entità binary_sensor.comelit_vedo_xxx
> > 
> > How do I install the new integration?
> 
> You need to put the 'comelit' under the custom_components/ folder. Then you need to update the configuration.yml file.

i have done what you wrote but nothing happened

**Comment by maurilloh** [comment] 2023-06-08 18:48
I have found this error if it help: Error while setting up comelit platform for binary_sensorTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/comelit/binary_sensor.py", line 13, in async_setup_platform if hass.data[DOMAIN]['hub'] is not None: ~~~~~~~~~~~~~~~~~^^^^^^^ KeyError: 'hub'

**Comment by Vincenzopica** [comment] 2023-06-08 18:49
> 

me too nothing

**Comment by Vincenzopica** [comment] 2023-06-08 19:11
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.comelit.vedo
Source: custom_components/comelit/vedo.py:282
Integration: Comelit SimpleHome/Vedo (documentation, issues)
First occurred: 21:07:22 (1 occurrences)
Last logged: 21:07:22

Error getting data! cookie expired

**Comment by Vincenzopica** [comment] 2023-06-08 19:11
Logger: homeassistant.components.binary_sensor
Source: custom_components/comelit/binary_sensor.py:13
Integration: Sensore binario (documentation, issues)
First occurred: 21:05:21 (1 occurrences)
Last logged: 21:05:21

Error while setting up comelit platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/comelit/binary_sensor.py", line 13, in async_setup_platform
    if hass.data[DOMAIN]['hub'] is not None:
KeyError: 'hub'

**Comment by gicamm** [comment] 2023-06-09 04:28
You haven't the hub, that explains the issue.
I made a change. Please confirm if it works.

**Comment by Vincenzopica** [comment] 2023-06-09 04:55
> You haven't the hub, that explains the issue. I made a change. Please confirm if it works.

how do i make the changes?

**Comment by gicamm** [comment] 2023-06-09 06:06
> > You haven't the hub, that explains the issue. I made a change. Please confirm if it works.
> 
> how do i make the changes?

you need to download the new integration from [here](https://github.com/gicamm/homeassistant-comelit/archive/refs/heads/42-add-vedo-sensors.zip)

**Comment by maurilloh** [comment] 2023-06-09 07:24
> You haven't the hub, that explains the issue. I made a change. Please confirm if it works.

Hi Gicamm,

it works for the motion sensors (i see off in the state at the moment) while the door and window sensors do not appear

i don's see any errors in the log

**Comment by gicamm** [comment] 2023-06-09 08:08
I cannot test the door sensors, so that it couldn't be supported.

**Comment by maurilloh** [comment] 2023-06-09 08:36
> I cannot test the door sensors, so that it couldn't be supported.

Ok but you know why only two motion sensors are visibile and not three?

If there is a way to help you to support also the door sensor please let me know, i would glad to help you

**Comment by gicamm** [comment] 2023-06-09 08:39
> > I cannot test the door sensors, so that it couldn't be supported.
> 
> Ok but you know why only two motion sensors are visibile and not three?
> 
> If there is a way to help you to support also the door sensor please let me know, i would glad to help you

Mmm, strange.
Everyone who can contribute is welcome. You can add support to door sensors.

**Comment by maurilloh** [comment] 2023-06-09 08:43
> > > I cannot test the door sensors, so that it couldn't be supported.
> > 
> > 
> > Ok but you know why only two motion sensors are visibile and not three?
> > If there is a way to help you to support also the door sensor please let me know, i would glad to help you
> 
> Mmm, strange. Everyone who can contribute is welcome. You can add support to door sensors.

Hi Gicamm,

no, I'm not able, I was wondering if I could help you implement them but with your help

**Comment by maurilloh** [comment] 2023-06-09 10:27
If can help you i found this project:

https://github.com/madchicken/comelit-client

with this command: vedo -h VEDO_IP -p PORT zone --status --desc --code <ARM/DISARM CODE>

i received this:

ecuting zone status call
[
  {
    index: 1,
    description: 'Zona 24H',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 3,
    description: 'PORTA CUCINA',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 5,
    description: 'FINESTRA CUCINA',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 7,
    description: 'P.FIN. SALA',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 9,
    description: 'PORTONE ING.',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 11,
    description: 'FIN. SALA',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 13,
    description: 'BAGNO',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 15,
    description: 'FIN. GARAGE',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 17,
    description: 'RIV. GARAGE',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 19,
    description: 'CAM. LATO ING.',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 21,
    description: 'BAGNO CAMERA',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 23,
    description: 'CAM. MATRIM.',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 25,
    description: 'CAMERA A',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 147,
    description: 'RIV. GIORNO',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  },
  {
    index: 149,
    description: 'RIV. NOTTE',
    open: false,
    excluded: false,
    isolated: false,
    sabotated: false,
    alarm: false,
    inhibited: false
  }
]

maybe you can integrate it in your project for binary sensor.

**Comment by maurilloh** [comment] 2023-06-09 11:33
> > You haven't the hub, that explains the issue. I made a change. Please confirm if it works.
> 
> Hi Gicamm,
> 
> it works for the motion sensors (i see off in the state at the moment) while the door and window sensors do not appear.
> I have three motion sensors but only two are visibile in the entities list
> 
> i don's see any errors in the log

i am at home now but the motion sensors don't change, they are off all time

**Comment by Vincenzopica** [comment] 2023-06-09 15:56
ciao, 
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.comelit.vedo
Source: custom_components/comelit/vedo.py:282
Integration: Comelit SimpleHome/Vedo (documentation, issues)
First occurred: 17:49:37 (2 occurrences)
Last logged: 17:52:11

Error getting data! cookie expired

**Comment by gicamm** [comment] 2023-06-09 16:04
> > > You haven't the hub, that explains the issue. I made a change. Please confirm if it works.
> > 
> > 
> > Hi Gicamm,
> > it works for the motion sensors (i see off in the state at the moment) while the door and window sensors do not appear.
> > I have three motion sensors but only two are visibile in the entities list
> > i don's see any errors in the log
> 
> i am at home now but the motion sensors don't change, they are off all time

Setting the scan_interval to 30s is challenging to catch the change.

Anyway, to be clear. The Vedo API isn't designed for this kind of stuff. The integration needs to be continuously logged in. With the comelit hub, they did a good job since they moved to mqtt. So That's the reason why I did not integrate binary sensors, and maybe it will never be integrated.

**Comment by gicamm** [comment] 2023-06-09 23:47
Please update with the latest code. Then change the log levels.
```
logger:
  default: warn
  logs:
    custom_components.comelit.hub: info
    custom_components.comelit.vedo: debug
```
I'm running the integration without issues, but maybe something could be different.

**Comment by Vincenzopica** [comment] 2023-06-10 06:32
> Please update with the latest code. Then change the log levels.
> 
> ```
> logger:
>   default: warn
>   logs:
>     custom_components.comelit.hub: info
>     custom_components.comelit.vedo: debug
> ```
> 
> I'm running the integration without issues, but maybe something could be different.

![registro](https://github.com/gicamm/homeassistant-comelit/assets/101067938/c6713a9f-7732-486c-966a-5a199dd7f51d)

**Comment by piergigi92** [comment] 2023-06-19 09:38
> > Please update with the latest code. Then change the log levels.
> > ```
> > logger:
> >   default: warn
> >   logs:
> >     custom_components.comelit.hub: info
> >     custom_components.comelit.vedo: debug
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm running the integration without issues, but maybe something could be different.
> 
> ![registro](https://user-images.githubusercontent.com/101067938/244852587-c6713a9f-7732-486c-966a-5a199dd7f51d.png)

Vincenzo hai risolto?
Neanche io vedo i binary.sensors dopo aver aggiornato l'integrazione e modificato il configuration.yaml

**Comment by stefanojan** [comment] 2023-09-11 19:31
Se ti può essere d'aiuto ho notato che con l'app comelit non c'è bisogno di effettuare il login per vedere lo stato dei sensori. Anche io sarei molto interessato e ti nel mio piccolo vorrei darti una mano per rendere possibile l'integrazione di Comelit Vedo su Home Assistant

**Comment by stefanojan** [comment] 2023-09-19 09:19
Tramite richieste post ho estrapolato questi codici dai sensori che ho in casa
sensore porta finestra 0000 off 0011 on
sensore contatto 0000 off 0001
sensore movimento 0000 off 0001
0020 zona Inserita
0100 zona Isolata
0080 zona Eslusa
0200 zona disabilitata vuota

**Comment by gicamm** [comment] 2023-09-19 12:33
> Tramite richieste post ho estrapolato questi codici dai sensori che ho in casa sensore porta finestra 0000 off 0011 on sensore contatto 0000 off 0001 sensore movimento 0000 off 0001 0020 zona Inserita 0100 zona Isolata 0080 zona Eslusa 0200 zona disabilitata vuota

OK. daro' un'occhiata

**Comment by stefanojan** [comment] 2023-09-19 15:06
> > Tramite richieste post ho estrapolato questi codici dai sensori che ho in casa sensore porta finestra 0000 off 0011 on sensore contatto 0000 off 0001 sensore movimento 0000 off 0001 0020 zona Inserita 0100 zona Isolata 0080 zona Eslusa 0200 zona disabilitata vuota
> 
> OK. daro' un'occhiata

Grazie, appena posso testo anche la zona in allarme e sabotata

**Comment by gicamm** [comment] 2024-06-02 07:43
Hello everyone,
It's been a long time :D.
I have just made some changes to the '42-add-vedo-sensors' branch.

You need to enable binary sensors (binary_sensors: enable)
The configuration should look something like this

```
vedo:
  host: X.X.X.X
  port: 80
  password: xxxxxx
  scan_interval: 30
  binary_sensors: enable

```
You can reduce the scan_interval to get new data more frequently. 30 is too much for motion sensors.

You'll see new entities binary_sensor.comelit_vedo_xxx

Can you help with testing?

**Closed** 2024-06-03 08:14 UTC
Labels: enhancement
